### ISSUE TITLE
Add clean_strongloop.sh script

### ISSUE THREAD

**Issue by zbal** [wiredcraft-ops/role-wcl-strongloop#1]
Strongloop creates a lot of files in `/var/lib/strongpm/svc/{SVC}/work` and does not remove them.

Create a script that will clean those files.

Notes:
- try to get the list of running services running (`slc ctl` - and match a name vs a service id)
- submit the list to the user and ask for the service ID to clean
- ask for the number of versions to keep (default: 2)
- do the cleanup
- add support for parameters like `-s 1 -c 2` (service ID 1, count 2)

---

Consider using the following bash code for the options management

```
show_help() {
    echo 'Options:  
    -s, --svc              Service ID (default: 1)
    -c, --count              Version kept (default: 2)
    -h, --help              Show this help
'
}


get_options() {
    OPTION=$(getopt --options s:c:h \
             --long svc:,count:,help \
             -- "$@")

    # exit if the options have not properly been gathered
    if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

    # Note the quotes around '$OPTION': they are essential!
    eval set -- "$OPTION"

  while true ; do
      case "$1" in
        -s|--svc) SVC="$2" ; shift 2 ;;
        -c|--count) COUNT="$2" ; shift 2 ;;
        -h|--help) show_help ;exit 1 ;;
        --) shift; break;;
        *) echo "Internal error!" ; exit 1 ;;
      esac
    done
}
get_options "$@"

# Set the defaults if no data provided on the CLI
if [ -z "$SVC" ]; then
    SVC=1
fi

if [ -z "$COUNT" ]; then
    COUNT=2
fi
```

**Comment by zbal** [comment]
Include that script to `/usr/local/bin/slc_clean` (and set the right permissions / exec right)

**Comment by sunsongxp** [comment]
I created an PR: https://github.com/wiredcraft-ops/role-wcl-strongloop/pull/2, in this PR, the support of keeping last number of versions haven't been added. so `--count` does not work for now.
